// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/download_manager.dart';
import 'api/url_ext.dart';
import 'api/video_caching.dart';
import 'api/video_proxy.dart';
import 'dart:async';
import 'dart:convert';
import 'download/download_status.dart';
import 'frb_generated.dart';
import 'global/cache_key_config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'proxy/platform_kind.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<DownloadTaskInfo> dco_decode_StreamSink_download_task_info_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PrecacheProgressInfo>
  dco_decode_StreamSink_precache_progress_info_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CacheKeyConfig dco_decode_box_autoadd_cache_key_config(dynamic raw);

  @protected
  HlsMasterPlaylistInfo dco_decode_box_autoadd_hls_master_playlist_info(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  CacheKeyConfig dco_decode_cache_key_config(dynamic raw);

  @protected
  DownloadStatus dco_decode_download_status(dynamic raw);

  @protected
  DownloadTaskInfo dco_decode_download_task_info(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HlsMasterPlaylistInfo dco_decode_hls_master_playlist_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DownloadTaskInfo> dco_decode_list_download_task_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<PrecacheProgressInfo>?
  dco_decode_opt_StreamSink_precache_progress_info_Sse(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  HlsMasterPlaylistInfo? dco_decode_opt_box_autoadd_hls_master_playlist_info(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  PlatformKind dco_decode_platform_kind(dynamic raw);

  @protected
  PrecacheProgressInfo dco_decode_precache_progress_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DownloadTaskInfo> sse_decode_StreamSink_download_task_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PrecacheProgressInfo>
  sse_decode_StreamSink_precache_progress_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CacheKeyConfig sse_decode_box_autoadd_cache_key_config(
    SseDeserializer deserializer,
  );

  @protected
  HlsMasterPlaylistInfo sse_decode_box_autoadd_hls_master_playlist_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  CacheKeyConfig sse_decode_cache_key_config(SseDeserializer deserializer);

  @protected
  DownloadStatus sse_decode_download_status(SseDeserializer deserializer);

  @protected
  DownloadTaskInfo sse_decode_download_task_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HlsMasterPlaylistInfo sse_decode_hls_master_playlist_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DownloadTaskInfo> sse_decode_list_download_task_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PrecacheProgressInfo>?
  sse_decode_opt_StreamSink_precache_progress_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  HlsMasterPlaylistInfo? sse_decode_opt_box_autoadd_hls_master_playlist_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  PlatformKind sse_decode_platform_kind(SseDeserializer deserializer);

  @protected
  PrecacheProgressInfo sse_decode_precache_progress_info(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_task_info_Sse(
    RustStreamSink<DownloadTaskInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_precache_progress_info_Sse(
    RustStreamSink<PrecacheProgressInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cache_key_config(
    CacheKeyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hls_master_playlist_info(
    HlsMasterPlaylistInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_cache_key_config(
    CacheKeyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_status(
    DownloadStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_task_info(
    DownloadTaskInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_hls_master_playlist_info(
    HlsMasterPlaylistInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_task_info(
    List<DownloadTaskInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_StreamSink_precache_progress_info_Sse(
    RustStreamSink<PrecacheProgressInfo>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_hls_master_playlist_info(
    HlsMasterPlaylistInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_platform_kind(PlatformKind self, SseSerializer serializer);

  @protected
  void sse_encode_precache_progress_info(
    PrecacheProgressInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
