// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/download_manager.dart';
import 'api/url_ext.dart';
import 'api/video_caching.dart';
import 'api/video_proxy.dart';
import 'dart:async';
import 'dart:convert';
import 'download/download_status.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'global/cache_key_config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'proxy/platform_kind.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 685478372;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'xue_hua_video_cache',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<DownloadTaskInfo>>
  crateApiDownloadManagerDownloadManagerAllTasks();

  Future<void> crateApiDownloadManagerDownloadManagerCancelAllTasks();

  Future<void> crateApiDownloadManagerDownloadManagerCancelTaskAboutUrl({
    required String url,
  });

  Future<void> crateApiDownloadManagerDownloadManagerCancelTaskById({
    required String taskId,
  });

  Future<void> crateApiDownloadManagerDownloadManagerCancelTaskByUrl({
    required String url,
  });

  Future<List<DownloadTaskInfo>>
  crateApiDownloadManagerDownloadManagerDownloadingTasks();

  Future<void> crateApiDownloadManagerDownloadManagerPauseAllTasks();

  Future<void> crateApiDownloadManagerDownloadManagerPauseTaskById({
    required String taskId,
  });

  Future<void> crateApiDownloadManagerDownloadManagerPauseTaskByUrl({
    required String url,
  });

  Future<void> crateApiDownloadManagerDownloadManagerResumeTaskById({
    required String taskId,
  });

  Future<void> crateApiDownloadManagerDownloadManagerResumeTaskByUrl({
    required String url,
  });

  Stream<DownloadTaskInfo> crateApiDownloadManagerDownloadManagerSubscribe();

  String crateApiUrlExtGenerateMd5Str({required String input});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiVideoCachingLruRemoveCacheByUrl({
    required String url,
    required bool singleFile,
  });

  Future<void> crateApiVideoProxySetCacheRootPath({required String path});

  String crateApiUrlExtToLocalUrlStr({required String url});

  String crateApiUrlExtToOriginUrlStr({required String url});

  String crateApiUrlExtToSafeUrlStr({required String url});

  Future<bool> crateApiVideoCachingVideoCachingIsCached({
    required String url,
    Map<String, String>? headers,
    required int cacheSegments,
  });

  Future<HlsMasterPlaylistInfo?>
  crateApiVideoCachingVideoCachingParseHlsMasterPlaylist({
    required String url,
    Map<String, String>? headers,
  });

  Future<void> crateApiVideoCachingVideoCachingPrecache({
    required String url,
    Map<String, String>? headers,
    required int cacheSegments,
    required bool downloadNow,
    required bool progressListen,
    RustStreamSink<PrecacheProgressInfo>? sink,
  });

  Future<void> crateApiVideoProxyVideoProxyDispose();

  Future<void> crateApiVideoProxyVideoProxyInit({
    String? ip,
    int? port,
    required PlatformInt64 maxMemoryCacheSize,
    required PlatformInt64 maxStorageCacheSize,
    required String cacheDir,
    required bool logPrint,
    required PlatformInt64 segmentSize,
    required int maxConcurrentDownloads,
    required PlatformKind platform,
    required CacheKeyConfig cacheKeyConfig,
  });

  Future<bool> crateApiVideoProxyVideoProxyIsRunning();

  Future<void> crateApiVideoProxyVideoProxyRestart();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<DownloadTaskInfo>>
  crateApiDownloadManagerDownloadManagerAllTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_download_task_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadManagerDownloadManagerAllTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadManagerDownloadManagerAllTasksConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_all_tasks",
        argNames: [],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerCancelAllTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerCancelAllTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerCancelAllTasksConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_cancel_all_tasks",
        argNames: [],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerCancelTaskAboutUrl({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerCancelTaskAboutUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerCancelTaskAboutUrlConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_cancel_task_about_url",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerCancelTaskById({
    required String taskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerCancelTaskByIdConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerCancelTaskByIdConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_cancel_task_by_id",
        argNames: ["taskId"],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerCancelTaskByUrl({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerCancelTaskByUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerCancelTaskByUrlConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_cancel_task_by_url",
        argNames: ["url"],
      );

  @override
  Future<List<DownloadTaskInfo>>
  crateApiDownloadManagerDownloadManagerDownloadingTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_download_task_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerDownloadingTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerDownloadingTasksConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_downloading_tasks",
        argNames: [],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerPauseAllTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerPauseAllTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerPauseAllTasksConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_pause_all_tasks",
        argNames: [],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerPauseTaskById({
    required String taskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerPauseTaskByIdConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerPauseTaskByIdConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_pause_task_by_id",
        argNames: ["taskId"],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerPauseTaskByUrl({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerPauseTaskByUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerPauseTaskByUrlConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_pause_task_by_url",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerResumeTaskById({
    required String taskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerResumeTaskByIdConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerResumeTaskByIdConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_resume_task_by_id",
        argNames: ["taskId"],
      );

  @override
  Future<void> crateApiDownloadManagerDownloadManagerResumeTaskByUrl({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDownloadManagerDownloadManagerResumeTaskByUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDownloadManagerDownloadManagerResumeTaskByUrlConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_resume_task_by_url",
        argNames: ["url"],
      );

  @override
  Stream<DownloadTaskInfo> crateApiDownloadManagerDownloadManagerSubscribe() {
    final sink = RustStreamSink<DownloadTaskInfo>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_download_task_info_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiDownloadManagerDownloadManagerSubscribeConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloadManagerDownloadManagerSubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "download_manager_subscribe",
        argNames: ["sink"],
      );

  @override
  String crateApiUrlExtGenerateMd5Str({required String input}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUrlExtGenerateMd5StrConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrlExtGenerateMd5StrConstMeta =>
      const TaskConstMeta(debugName: "generate_md5_str", argNames: ["input"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiVideoCachingLruRemoveCacheByUrl({
    required String url,
    required bool singleFile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_bool(singleFile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoCachingLruRemoveCacheByUrlConstMeta,
        argValues: [url, singleFile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoCachingLruRemoveCacheByUrlConstMeta =>
      const TaskConstMeta(
        debugName: "lru_remove_cache_by_url",
        argNames: ["url", "singleFile"],
      );

  @override
  Future<void> crateApiVideoProxySetCacheRootPath({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVideoProxySetCacheRootPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoProxySetCacheRootPathConstMeta =>
      const TaskConstMeta(debugName: "set_cache_root_path", argNames: ["path"]);

  @override
  String crateApiUrlExtToLocalUrlStr({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUrlExtToLocalUrlStrConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrlExtToLocalUrlStrConstMeta =>
      const TaskConstMeta(debugName: "to_local_url_str", argNames: ["url"]);

  @override
  String crateApiUrlExtToOriginUrlStr({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUrlExtToOriginUrlStrConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrlExtToOriginUrlStrConstMeta =>
      const TaskConstMeta(debugName: "to_origin_url_str", argNames: ["url"]);

  @override
  String crateApiUrlExtToSafeUrlStr({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUrlExtToSafeUrlStrConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrlExtToSafeUrlStrConstMeta =>
      const TaskConstMeta(debugName: "to_safe_url_str", argNames: ["url"]);

  @override
  Future<bool> crateApiVideoCachingVideoCachingIsCached({
    required String url,
    Map<String, String>? headers,
    required int cacheSegments,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_Map_String_String_None(headers, serializer);
          sse_encode_i_32(cacheSegments, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoCachingVideoCachingIsCachedConstMeta,
        argValues: [url, headers, cacheSegments],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoCachingVideoCachingIsCachedConstMeta =>
      const TaskConstMeta(
        debugName: "video_caching_is_cached",
        argNames: ["url", "headers", "cacheSegments"],
      );

  @override
  Future<HlsMasterPlaylistInfo?>
  crateApiVideoCachingVideoCachingParseHlsMasterPlaylist({
    required String url,
    Map<String, String>? headers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_Map_String_String_None(headers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_hls_master_playlist_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiVideoCachingVideoCachingParseHlsMasterPlaylistConstMeta,
        argValues: [url, headers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiVideoCachingVideoCachingParseHlsMasterPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "video_caching_parse_hls_master_playlist",
        argNames: ["url", "headers"],
      );

  @override
  Future<void> crateApiVideoCachingVideoCachingPrecache({
    required String url,
    Map<String, String>? headers,
    required int cacheSegments,
    required bool downloadNow,
    required bool progressListen,
    RustStreamSink<PrecacheProgressInfo>? sink,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_Map_String_String_None(headers, serializer);
          sse_encode_i_32(cacheSegments, serializer);
          sse_encode_bool(downloadNow, serializer);
          sse_encode_bool(progressListen, serializer);
          sse_encode_opt_StreamSink_precache_progress_info_Sse(
            sink,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoCachingVideoCachingPrecacheConstMeta,
        argValues: [
          url,
          headers,
          cacheSegments,
          downloadNow,
          progressListen,
          sink,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoCachingVideoCachingPrecacheConstMeta =>
      const TaskConstMeta(
        debugName: "video_caching_precache",
        argNames: [
          "url",
          "headers",
          "cacheSegments",
          "downloadNow",
          "progressListen",
          "sink",
        ],
      );

  @override
  Future<void> crateApiVideoProxyVideoProxyDispose() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoProxyVideoProxyDisposeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoProxyVideoProxyDisposeConstMeta =>
      const TaskConstMeta(debugName: "video_proxy_dispose", argNames: []);

  @override
  Future<void> crateApiVideoProxyVideoProxyInit({
    String? ip,
    int? port,
    required PlatformInt64 maxMemoryCacheSize,
    required PlatformInt64 maxStorageCacheSize,
    required String cacheDir,
    required bool logPrint,
    required PlatformInt64 segmentSize,
    required int maxConcurrentDownloads,
    required PlatformKind platform,
    required CacheKeyConfig cacheKeyConfig,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(ip, serializer);
          sse_encode_opt_box_autoadd_u_16(port, serializer);
          sse_encode_i_64(maxMemoryCacheSize, serializer);
          sse_encode_i_64(maxStorageCacheSize, serializer);
          sse_encode_String(cacheDir, serializer);
          sse_encode_bool(logPrint, serializer);
          sse_encode_i_64(segmentSize, serializer);
          sse_encode_u_32(maxConcurrentDownloads, serializer);
          sse_encode_platform_kind(platform, serializer);
          sse_encode_box_autoadd_cache_key_config(cacheKeyConfig, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoProxyVideoProxyInitConstMeta,
        argValues: [
          ip,
          port,
          maxMemoryCacheSize,
          maxStorageCacheSize,
          cacheDir,
          logPrint,
          segmentSize,
          maxConcurrentDownloads,
          platform,
          cacheKeyConfig,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoProxyVideoProxyInitConstMeta =>
      const TaskConstMeta(
        debugName: "video_proxy_init",
        argNames: [
          "ip",
          "port",
          "maxMemoryCacheSize",
          "maxStorageCacheSize",
          "cacheDir",
          "logPrint",
          "segmentSize",
          "maxConcurrentDownloads",
          "platform",
          "cacheKeyConfig",
        ],
      );

  @override
  Future<bool> crateApiVideoProxyVideoProxyIsRunning() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoProxyVideoProxyIsRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoProxyVideoProxyIsRunningConstMeta =>
      const TaskConstMeta(debugName: "video_proxy_is_running", argNames: []);

  @override
  Future<void> crateApiVideoProxyVideoProxyRestart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVideoProxyVideoProxyRestartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoProxyVideoProxyRestartConstMeta =>
      const TaskConstMeta(debugName: "video_proxy_restart", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<DownloadTaskInfo> dco_decode_StreamSink_download_task_info_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PrecacheProgressInfo>
  dco_decode_StreamSink_precache_progress_info_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CacheKeyConfig dco_decode_box_autoadd_cache_key_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_cache_key_config(raw);
  }

  @protected
  HlsMasterPlaylistInfo dco_decode_box_autoadd_hls_master_playlist_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_hls_master_playlist_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CacheKeyConfig dco_decode_cache_key_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return CacheKeyConfig(ignoreQueryKeys: dco_decode_list_String(arr[0]));
  }

  @protected
  DownloadStatus dco_decode_download_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DownloadStatus.values[raw as int];
  }

  @protected
  DownloadTaskInfo dco_decode_download_task_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DownloadTaskInfo(
      id: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      priority: dco_decode_i_32(arr[2]),
      progress: dco_decode_f_64(arr[3]),
      cachedBytes: dco_decode_i_64(arr[4]),
      downloadedBytes: dco_decode_i_64(arr[5]),
      totalBytes: dco_decode_i_64(arr[6]),
      status: dco_decode_download_status(arr[7]),
      hlsKey: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HlsMasterPlaylistInfo dco_decode_hls_master_playlist_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return HlsMasterPlaylistInfo(
      mediaPlaylistUrls: dco_decode_list_String(arr[0]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DownloadTaskInfo> dco_decode_list_download_task_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_download_task_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_Map_String_String_None(raw);
  }

  @protected
  RustStreamSink<PrecacheProgressInfo>?
  dco_decode_opt_StreamSink_precache_progress_info_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_StreamSink_precache_progress_info_Sse(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  HlsMasterPlaylistInfo? dco_decode_opt_box_autoadd_hls_master_playlist_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_hls_master_playlist_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  PlatformKind dco_decode_platform_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlatformKind.values[raw as int];
  }

  @protected
  PrecacheProgressInfo dco_decode_precache_progress_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return PrecacheProgressInfo(
      progress: dco_decode_f_64(arr[0]),
      url: dco_decode_String(arr[1]),
      startRange: dco_decode_opt_box_autoadd_i_64(arr[2]),
      endRange: dco_decode_opt_box_autoadd_i_64(arr[3]),
      segmentUrl: dco_decode_opt_String(arr[4]),
      parentUrl: dco_decode_opt_String(arr[5]),
      fileName: dco_decode_opt_String(arr[6]),
      hlsKey: dco_decode_opt_String(arr[7]),
      totalSegments: dco_decode_opt_box_autoadd_i_32(arr[8]),
      currentSegmentIndex: dco_decode_opt_box_autoadd_i_32(arr[9]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<DownloadTaskInfo> sse_decode_StreamSink_download_task_info_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PrecacheProgressInfo>
  sse_decode_StreamSink_precache_progress_info_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CacheKeyConfig sse_decode_box_autoadd_cache_key_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_cache_key_config(deserializer));
  }

  @protected
  HlsMasterPlaylistInfo sse_decode_box_autoadd_hls_master_playlist_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_hls_master_playlist_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  CacheKeyConfig sse_decode_cache_key_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ignoreQueryKeys = sse_decode_list_String(deserializer);
    return CacheKeyConfig(ignoreQueryKeys: var_ignoreQueryKeys);
  }

  @protected
  DownloadStatus sse_decode_download_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DownloadStatus.values[inner];
  }

  @protected
  DownloadTaskInfo sse_decode_download_task_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_priority = sse_decode_i_32(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_cachedBytes = sse_decode_i_64(deserializer);
    var var_downloadedBytes = sse_decode_i_64(deserializer);
    var var_totalBytes = sse_decode_i_64(deserializer);
    var var_status = sse_decode_download_status(deserializer);
    var var_hlsKey = sse_decode_opt_String(deserializer);
    return DownloadTaskInfo(
      id: var_id,
      url: var_url,
      priority: var_priority,
      progress: var_progress,
      cachedBytes: var_cachedBytes,
      downloadedBytes: var_downloadedBytes,
      totalBytes: var_totalBytes,
      status: var_status,
      hlsKey: var_hlsKey,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HlsMasterPlaylistInfo sse_decode_hls_master_playlist_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mediaPlaylistUrls = sse_decode_list_String(deserializer);
    return HlsMasterPlaylistInfo(mediaPlaylistUrls: var_mediaPlaylistUrls);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DownloadTaskInfo> sse_decode_list_download_task_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DownloadTaskInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_download_task_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_Map_String_String_None(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustStreamSink<PrecacheProgressInfo>?
  sse_decode_opt_StreamSink_precache_progress_info_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_StreamSink_precache_progress_info_Sse(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HlsMasterPlaylistInfo? sse_decode_opt_box_autoadd_hls_master_playlist_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_hls_master_playlist_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformKind sse_decode_platform_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlatformKind.values[inner];
  }

  @protected
  PrecacheProgressInfo sse_decode_precache_progress_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_64(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_startRange = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_endRange = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_segmentUrl = sse_decode_opt_String(deserializer);
    var var_parentUrl = sse_decode_opt_String(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    var var_hlsKey = sse_decode_opt_String(deserializer);
    var var_totalSegments = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_currentSegmentIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    return PrecacheProgressInfo(
      progress: var_progress,
      url: var_url,
      startRange: var_startRange,
      endRange: var_endRange,
      segmentUrl: var_segmentUrl,
      parentUrl: var_parentUrl,
      fileName: var_fileName,
      hlsKey: var_hlsKey,
      totalSegments: var_totalSegments,
      currentSegmentIndex: var_currentSegmentIndex,
    );
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_download_task_info_Sse(
    RustStreamSink<DownloadTaskInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_task_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_precache_progress_info_Sse(
    RustStreamSink<PrecacheProgressInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_precache_progress_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_cache_key_config(
    CacheKeyConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cache_key_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_hls_master_playlist_info(
    HlsMasterPlaylistInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_hls_master_playlist_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_cache_key_config(
    CacheKeyConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.ignoreQueryKeys, serializer);
  }

  @protected
  void sse_encode_download_status(
    DownloadStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_download_task_info(
    DownloadTaskInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_i_32(self.priority, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_i_64(self.cachedBytes, serializer);
    sse_encode_i_64(self.downloadedBytes, serializer);
    sse_encode_i_64(self.totalBytes, serializer);
    sse_encode_download_status(self.status, serializer);
    sse_encode_opt_String(self.hlsKey, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_hls_master_playlist_info(
    HlsMasterPlaylistInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.mediaPlaylistUrls, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_download_task_info(
    List<DownloadTaskInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_download_task_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_Map_String_String_None(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_StreamSink_precache_progress_info_Sse(
    RustStreamSink<PrecacheProgressInfo>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_StreamSink_precache_progress_info_Sse(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_hls_master_playlist_info(
    HlsMasterPlaylistInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_hls_master_playlist_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_platform_kind(PlatformKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_precache_progress_info(
    PrecacheProgressInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.progress, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_box_autoadd_i_64(self.startRange, serializer);
    sse_encode_opt_box_autoadd_i_64(self.endRange, serializer);
    sse_encode_opt_String(self.segmentUrl, serializer);
    sse_encode_opt_String(self.parentUrl, serializer);
    sse_encode_opt_String(self.fileName, serializer);
    sse_encode_opt_String(self.hlsKey, serializer);
    sse_encode_opt_box_autoadd_i_32(self.totalSegments, serializer);
    sse_encode_opt_box_autoadd_i_32(self.currentSegmentIndex, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
