// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../download/download_status.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `task_to_info`, `tasks_to_info`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<DownloadTaskInfo> downloadManagerSubscribe() =>
    RustLib.instance.api.crateApiDownloadManagerDownloadManagerSubscribe();

Future<List<DownloadTaskInfo>> downloadManagerAllTasks() =>
    RustLib.instance.api.crateApiDownloadManagerDownloadManagerAllTasks();

Future<List<DownloadTaskInfo>> downloadManagerDownloadingTasks() => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerDownloadingTasks();

Future<void> downloadManagerPauseTaskById({required String taskId}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerPauseTaskById(taskId: taskId);

Future<void> downloadManagerResumeTaskById({required String taskId}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerResumeTaskById(taskId: taskId);

Future<void> downloadManagerCancelTaskById({required String taskId}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerCancelTaskById(taskId: taskId);

Future<void> downloadManagerPauseAllTasks() =>
    RustLib.instance.api.crateApiDownloadManagerDownloadManagerPauseAllTasks();

Future<void> downloadManagerCancelAllTasks() =>
    RustLib.instance.api.crateApiDownloadManagerDownloadManagerCancelAllTasks();

Future<void> downloadManagerCancelTaskByUrl({required String url}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerCancelTaskByUrl(url: url);

Future<void> downloadManagerPauseTaskByUrl({required String url}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerPauseTaskByUrl(url: url);

Future<void> downloadManagerResumeTaskByUrl({required String url}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerResumeTaskByUrl(url: url);

Future<void> downloadManagerCancelTaskAboutUrl({required String url}) => RustLib
    .instance
    .api
    .crateApiDownloadManagerDownloadManagerCancelTaskAboutUrl(url: url);

class DownloadTaskInfo {
  final String id;
  final String url;
  final int priority;
  final double progress;
  final PlatformInt64 cachedBytes;
  final PlatformInt64 downloadedBytes;
  final PlatformInt64 totalBytes;
  final DownloadStatus status;
  final String? hlsKey;

  const DownloadTaskInfo({
    required this.id,
    required this.url,
    required this.priority,
    required this.progress,
    required this.cachedBytes,
    required this.downloadedBytes,
    required this.totalBytes,
    required this.status,
    this.hlsKey,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      url.hashCode ^
      priority.hashCode ^
      progress.hashCode ^
      cachedBytes.hashCode ^
      downloadedBytes.hashCode ^
      totalBytes.hashCode ^
      status.hashCode ^
      hlsKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTaskInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          url == other.url &&
          priority == other.priority &&
          progress == other.progress &&
          cachedBytes == other.cachedBytes &&
          downloadedBytes == other.downloadedBytes &&
          totalBytes == other.totalBytes &&
          status == other.status &&
          hlsKey == other.hlsKey;
}
