// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String toLocalUrlStr({required String url}) =>
    RustLib.instance.api.crateApiUrlExtToLocalUrlStr(url: url);

String toOriginUrlStr({required String url}) =>
    RustLib.instance.api.crateApiUrlExtToOriginUrlStr(url: url);

String toSafeUrlStr({required String url}) =>
    RustLib.instance.api.crateApiUrlExtToSafeUrlStr(url: url);

String generateMd5Str({required String input}) =>
    RustLib.instance.api.crateApiUrlExtGenerateMd5Str(input: input);
