// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`

Future<void> videoCachingPrecache({
  required String url,
  Map<String, String>? headers,
  required int cacheSegments,
  required bool downloadNow,
  required bool progressListen,
  RustStreamSink<PrecacheProgressInfo>? sink,
}) => RustLib.instance.api.crateApiVideoCachingVideoCachingPrecache(
  url: url,
  headers: headers,
  cacheSegments: cacheSegments,
  downloadNow: downloadNow,
  progressListen: progressListen,
  sink: sink,
);

Future<bool> videoCachingIsCached({
  required String url,
  Map<String, String>? headers,
  required int cacheSegments,
}) => RustLib.instance.api.crateApiVideoCachingVideoCachingIsCached(
  url: url,
  headers: headers,
  cacheSegments: cacheSegments,
);

Future<HlsMasterPlaylistInfo?> videoCachingParseHlsMasterPlaylist({
  required String url,
  Map<String, String>? headers,
}) =>
    RustLib.instance.api.crateApiVideoCachingVideoCachingParseHlsMasterPlaylist(
      url: url,
      headers: headers,
    );

Future<void> lruRemoveCacheByUrl({
  required String url,
  required bool singleFile,
  Map<String, String>? headers,
}) => RustLib.instance.api.crateApiVideoCachingLruRemoveCacheByUrl(
  url: url,
  singleFile: singleFile,
  headers: headers,
);

class HlsMasterPlaylistInfo {
  final List<String> mediaPlaylistUrls;

  const HlsMasterPlaylistInfo({required this.mediaPlaylistUrls});

  @override
  int get hashCode => mediaPlaylistUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HlsMasterPlaylistInfo &&
          runtimeType == other.runtimeType &&
          mediaPlaylistUrls == other.mediaPlaylistUrls;
}

class PrecacheProgressInfo {
  final double progress;
  final String url;
  final PlatformInt64? startRange;
  final PlatformInt64? endRange;
  final String? segmentUrl;
  final String? parentUrl;
  final String? fileName;
  final String? hlsKey;
  final int? totalSegments;
  final int? currentSegmentIndex;

  const PrecacheProgressInfo({
    required this.progress,
    required this.url,
    this.startRange,
    this.endRange,
    this.segmentUrl,
    this.parentUrl,
    this.fileName,
    this.hlsKey,
    this.totalSegments,
    this.currentSegmentIndex,
  });

  @override
  int get hashCode =>
      progress.hashCode ^
      url.hashCode ^
      startRange.hashCode ^
      endRange.hashCode ^
      segmentUrl.hashCode ^
      parentUrl.hashCode ^
      fileName.hashCode ^
      hlsKey.hashCode ^
      totalSegments.hashCode ^
      currentSegmentIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrecacheProgressInfo &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          url == other.url &&
          startRange == other.startRange &&
          endRange == other.endRange &&
          segmentUrl == other.segmentUrl &&
          parentUrl == other.parentUrl &&
          fileName == other.fileName &&
          hlsKey == other.hlsKey &&
          totalSegments == other.totalSegments &&
          currentSegmentIndex == other.currentSegmentIndex;
}
