// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../global/cache_key_config.dart';
import '../proxy/platform_kind.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> videoProxyInit({
  String? ip,
  int? port,
  required PlatformInt64 maxMemoryCacheSize,
  required PlatformInt64 maxStorageCacheSize,
  required String cacheDir,
  required bool logPrint,
  required PlatformInt64 segmentSize,
  required int maxConcurrentDownloads,
  required PlatformKind platform,
  required CacheKeyConfig cacheKeyConfig,
}) => RustLib.instance.api.crateApiVideoProxyVideoProxyInit(
  ip: ip,
  port: port,
  maxMemoryCacheSize: maxMemoryCacheSize,
  maxStorageCacheSize: maxStorageCacheSize,
  cacheDir: cacheDir,
  logPrint: logPrint,
  segmentSize: segmentSize,
  maxConcurrentDownloads: maxConcurrentDownloads,
  platform: platform,
  cacheKeyConfig: cacheKeyConfig,
);

Future<void> videoProxyRestart() =>
    RustLib.instance.api.crateApiVideoProxyVideoProxyRestart();

Future<bool> videoProxyIsRunning() =>
    RustLib.instance.api.crateApiVideoProxyVideoProxyIsRunning();

Future<void> videoProxyDispose() =>
    RustLib.instance.api.crateApiVideoProxyVideoProxyDispose();

Future<void> setCacheRootPath({required String path}) =>
    RustLib.instance.api.crateApiVideoProxySetCacheRootPath(path: path);
