// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Cache key customization passed from Dart via FRB.
class CacheKeyConfig {
  /// Query parameter names to strip before computing the cache key (e.g. `token`).
  final List<String> ignoreQueryKeys;

  const CacheKeyConfig({required this.ignoreQueryKeys});

  @override
  int get hashCode => ignoreQueryKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheKeyConfig &&
          runtimeType == other.runtimeType &&
          ignoreQueryKeys == other.ignoreQueryKeys;
}
